### ISSUE TITLE
Covering mex interface in tests / octave support

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#1178]
I think it is not completely decided how Matlab support will look like in the future (see also #1161, #926). In case we keep the mex interface instead of using Python modules for simulation (which would probably be desirable in terms of performance when repeatedly simulating small models), we should really get that covered by automated tests. Due to the commercial nature of Matlab, we can't run Matlab stuff without setting up our own test servers. A quick search seems to show that we could very well use Octave to test the mex interface. Shouldn't be too difficult to set up. (Not talking about model import here.)
Official octave support may be interesting for some (not sure if things are fully compatible yet...)

**Comment by paulstapor** [comment]
Agree that Matlab functionality is mostly covered by Octave. However, I had a brief look and the API for compiling is different. Octave can compile legacy mex-files, but has a newer format now (oct-files). Some of the commands used in "compileAndLinkModel" seem not to work with octave (at east, that's what a quick test yielded): i.e., the mex command has a different structure what it returns.

I think it's doable to make an Octave interface out of it, with some changes at least on the Matlab side. However, this lowers the value of the automated test, since we would then test the octave interface, not the Matlab interface...
Yet, if the structure of at least the C++-side of the Matlab/Octave-interface would remain the same and could be automatedly tested, this would still be valuable. Shall I look into that a bit more closely at some point?

**Comment by dweindl** [comment]
> the mex command has a different structure what it returns.

I think if we can test everything but those 3 lines, we are a quite a bit further :)

> Shall I look into that a bit more closely at some point?

Not a priority for me. Needs some discussion about plan for future Matlab support in order to not waste too much effort there. But if we want to go there, I am sure happy about anybody jumping on that.

**Comment by FFroehlich** [comment]
I don't know who is planning to use the MATLAB interface. If those people would chime in here, that would be helpful.

**Comment by dweindl** [comment]
By now we can run matlab on GHA (#1449, #1451) without introducing additional maintenance burden. Therefore, closing.
