### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#1346]
Intel compiler complains about:

- [x] include/amici/vector.h(263): warning #858: type qualifier on return type is meaningless
- [x] include/amici/sundials_matrix_wrapper.h(115): warning #858: type qualifier on return type is meaningless

**Comment by thomassligon** [comment]
Interesting, this really does refer to the Intel compiler, and not the Microsoft compiler. The description of the warning is here:
[https://software.intel.com/content/www/us/en/develop/articles/cdiag858.html](https://software.intel.com/content/www/us/en/develop/articles/cdiag858.html)
which says:

Cause:
Compiler generates this warning when it finds a type qualifier applied to the return type of a function. C++ allows the type-qualifier to be const or volatile , but either qualifier applied to a function return type is meaningless, because functions can only return rvalues and the type qualifiers apply only to lvalues.

Resolution:
1. Remove the type qualifier from the return type of the function.
2. This diagnostic can be safely ignored.
