### ISSUE TITLE
petab models with observableParameter in petab.NOISE_FORMULA  should error

### ISSUE THREAD

**Issue by FFroehlich** [AMICI-dev/AMICI#1470]
Currently imported without complaints, model simulation works, but objective function value is inf.

**Comment by dweindl** [comment]
That should be fixed in the petab packages.

It's generally allowed to have `*observableParameter` in noise formulas, only they would not be treated as placeholders to be overwritten in the measurement table, but they would be just general output parameters that can be introduced in the observable table. Those parameters would have to be present in the parameter table, but they escape the current check (`petab.get_required_parameters_for_parameter_table`), because it's not checked line-by-line, but only globally, whether those parameters look like placeholders, but not if they are valid for the given location.
