### ISSUE TITLE
Change events in amici model object. 

### ISSUE THREAD

**Issue by Podde1** [AMICI-dev/AMICI#1484]
**Feature description**
[A clear and concise description of what you would like to have.]
Add possibility to add and remove events from a model object. This can maybe be done when declaring the SBMLImporter object or with the amici model-object. 
As an example: 
`model.addEvent(trigger, target, value)`
This does require that a symbolic expression for the time variable can be declared to make it possible for the trigger to act on time-based events and not only amount/concentration based events. 

`model.removeEvent(model.EventList[0])`
Remove an event (or more) from a list or such that contain all events in the model object (maybe `model.getEventId()` could be as an identifier) 

**Motivation/Application**
[Why is this feature useful?]
If one would like to alter the strengths of an event or change when it occurs, one is required to have a model description (SBML file) for each such case. If it were possible to alter the imported object it would be enough with one SBML-file, instead of having multiple identical files (only altering the event description). 
- This would allow for a more streamlined model development process, as one do not need to generate a new SBML file for each test one would like to do. 
 
With the added event support in amici 0.11.14, this would be a lovely build-on upon this.

**Comment by FFroehlich** [comment]
Hi,

Thank you for the input! AMICI is not geared for model development, but rather designed to offer reliable and fast simulation when models need less refinements and parameter estimation is to be performed. 

A model cannot be altered after import is performed since the model would have to be reimported. While it may be feasible to make simple changes in select cases, it is not doable in general. Implementing support for modifications that would allow for a more adaptive reimport would require substantial effort. Moreover, for small scale models, the computational cost of SBML import is negligible, as most of the effort is spent on model compilation. Accordingly, a more adaptive import would bring little actual benefit and I think it's generally more effective to simply modify the model with the same framework it was created with. 

The best way to work around this issue in AMICI is introducing additional parameters that can dynamically switch model features, such as reaction or events, on and off. This also allows you to later use model selection using L1 based approaches such as https://academic.oup.com/bioinformatics/article/32/17/i718/2450791

**Comment by Podde1** [comment]
Ye, I figured that it would not be feasible. However, one can always make sure :) 
Thanks for the input.
