### ISSUE TITLE
Error during Amici Simulation

### ISSUE THREAD

**Issue by vera-weber** [AMICI-dev/AMICI#1507]
When running `runAmiciSimulation` I get an error for a model that was specified with PEtab. The error is

`[Warning] AMICI:CVODES:CVode:WARNING: AMICI ERROR: in module CVODES in function CVode : Internal t = 73.0291 and h = 1.33929e-145 are such that t + h = t on the next step. The solver will continue anyway. 
[Warning] AMICI:simulation: AMICI simulation failed:
Cvode routine CVode returned a root after reinitialization. The initial step-size after the event or heaviside function is too small. To fix this, increase absolute and relative tolerances! failed with error code 2
`

The error was found when optimizing parameters using the Fides Optimizer. Especially, the timepoint at which an event happens, `t_2`, was optimized. The value for `t_2` is exactly the timepoint `t= 73.0291` at which the error occurs in `runAmiciSimulation`, so there might be a problem with the heaviside function. The error occurs when using forward sensitivities, not when using adjoint sensitivities. 

A working example of the problem including the PEtab files is here: [reproduce_issue.zip](https://github.com/AMICI-dev/AMICI/files/6483954/reproduce_issue.zip)

I am using amici version 0.11.16 on Kubuntu 20.04.

Any support regarding the cause of this error and how to resolve it is greatly appreciated. Thanks in advance!

**Comment by FFroehlich** [comment]
Dear Vera,

thanks for your interest in AMICI. This is an issue we frequently encounter with models with events. The issue is that the model requires a very small step size (`h = 1.33929e-145`) after post-event reinitialization. The error message already gives some hints on how the issue can be fixed. You can set the integration tolerances via https://amici.readthedocs.io/en/latest/generated/amici.amici.Solver.html#amici.amici.Solver.setRelativeTolerance and https://amici.readthedocs.io/en/latest/generated/amici.amici.Solver.html#amici.amici.Solver.setAbsoluteTolerance. You may also need to change respective values for the sensitivities via https://amici.readthedocs.io/en/latest/generated/amici.amici.Solver.html#amici.amici.Solver.setRelativeToleranceFSA and https://amici.readthedocs.io/en/latest/generated/amici.amici.Solver.html#amici.amici.Solver.setAbsoluteToleranceFSA
