### ISSUE TITLE
Forward simulation fails with NaN

### ISSUE THREAD

**Issue by matthiaskoenig** [AMICI-dev/AMICI#1781]
Hi all,
trying a forward simulation with the icg model but getting a lot of NaNs in the timecourse. It looks like the forward simulation fails.
With COPASI and roadrunner the model simulates without issues. Model and code attached.
[icg.zip](https://github.com/AMICI-dev/AMICI/files/8462594/icg.zip)

```python
from pathlib import Path

import petab
import amici.petab_import
import numpy as np
from amici.petab_import import import_petab_problem


output_dir: Path = Path(__file__).parent / "results" / "icg"
yaml_file: Path = output_dir / "icg.yaml"
model_file: Path = output_dir / "icg.xml"

# ---------------------------------------------------------------------------------------------------------------------
# Setup
# ---------------------------------------------------------------------------------------------------------------------
# Import yaml
petab_problem = petab.Problem.from_yaml(yaml_file)

# compile the petab problem to an AMICI ODE model
amici_model = amici.petab_import.import_petab_problem(petab_problem)

# Import PEtab problem to amici
amici_model = import_petab_problem(petab_problem)

# model properties
print("Model parameters:", list(amici_model.getParameterIds()), "\n")
print("Model const parameters:", list(amici_model.getFixedParameterIds()), "\n")
print("Model outputs:   ", list(amici_model.getObservableIds()), "\n")
print("Model states:    ", list(amici_model.getStateIds()), "\n")

# instantiate solver
solver = amici_model.getSolver()
solver.setAbsoluteTolerance(1e-10)

# run forward simulation
t = np.linspace(0, 20, num=201)
amici_model.setTimepoints(t)
rdata = amici.runAmiciSimulation(amici_model, solver)

print(t)
print(rdata.x)

import matplotlib.pyplot as plt
plt.plot(t, rdata.x)
plt.show()

# forward simulation with roadrunner
import roadrunner
import pandas as pd
r = roadrunner.RoadRunner(str(model_file))
s = r.simulate(0, 20, steps=200)
df = pd.DataFrame(s, columns=s.colnames)
print(df["time"])
print(df["[Cve_icg]"])

plt.plot(df["time"], df["[Cve_icg]"])
plt.show()
```
Results in 
```python
Model parameters: ['conversion_ml_per_l', 'conversion_l_per_ml', 'HEIGHT', 'COBW', 'Fblood', 'HCT', 'FVgi', 'FVbi', 'FVli', 'FVlu', 'FVve', 'FVar', 'FVpo', 'FVhv', 'FQgi', 'FQh', 'FQlu', 'f_cirrhosis', 'f_shunts', 'f_tissue_loss', 'f_bloodflow', 'f_cardiac_output', 'f_exercise', 'resection_rate', 'Mr_icg', 'ti_icg', 'LI__ICGIM_Vmax', 'LI__ICGIM_Km', 'LI__ICGIM_ki_bil', 'LI__f_oatp1b3', 'LI__ICGLI2CA_Vmax', 'LI__ICGLI2CA_Km', 'LI__ICGLI2BI_Vmax', 'noiseParameter1_Cve_icg', 'noiseParameter1_Chv_icg', 'noiseParameter1_Car_icg', 'noiseParameter1_ER_icg', 'noiseParameter1_LI__ICGLI2BI', 'initial_IVDOSE_icg_preeq', 'initial_IVDOSE_icg_sim'] 

Model const parameters: ['BW', 'Ri_icg', 'preequilibration_indicator'] 

Model outputs:    ['model__Cve_icg', 'model__Chv_icg', 'model__Car_icg', 'model__ER_icg', 'model__LI__ICGLI2BI'] 

Model states:     ['Cre_plasma_icg', 'Cgi_plasma_icg', 'Cli_plasma_icg', 'Clu_plasma_icg', 'Cve_icg', 'Car_icg', 'Cpo_icg', 'Chv_icg', 'Afeces_icg', 'LI__bil_ext', 'LI__icg', 'LI__icg_bi', 'IVDOSE_icg', 'cum_dose_icg'] 

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.  11.1
 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3 12.4 12.5
 12.6 12.7 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9
 14.  14.1 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.  15.1 15.2 15.3
 15.4 15.5 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4 16.5 16.6 16.7
 16.8 16.9 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.  18.1
 18.2 18.3 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2 19.3 19.4 19.5
 19.6 19.7 19.8 19.9 20. ]
[[ 0.  0.  0. ...  0. nan  0.]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
[Warning] AMICI:NaN: AMICI encountered a NaN value for fxdot[4]!
[Warning] AMICI:NaN: AMICI encountered a NaN value for k[2]!
[Warning] AMICI:NaN: AMICI encountered a NaN value for p[38]!
[Warning] AMICI:NaN: AMICI encountered a NaN value for w[56]!
[Warning] AMICI:CVODES:CVode:OTHER: AMICI ERROR: in module CVODES in function CVode : The right-hand side routine failed at the first call. 
[Warning] AMICI:simulation: AMICI forward simulation failed at t = 0.000000:
AMICI failed to integrate the forward problem

0       0.0
1       0.1
2       0.2
3       0.3
4       0.4
       ... 
196    19.6
197    19.7
198    19.8
199    19.9
200    20.0
Name: time, Length: 201, dtype: float64
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
196    0.0
197    0.0
198    0.0
199    0.0
200    0.0
Name: [Cve_icg], Length: 201, dtype: float64
```
edit: code formating

**Comment by FFroehlich** [comment]
Hi Matthias, 

The reason why simulation fails is that some of the parameters/constants in the model are nan (as indicated by the error message
```
[Warning] AMICI:NaN: AMICI encountered a NaN value for k[2]!
[Warning] AMICI:NaN: AMICI encountered a NaN value for p[38]!
```

Specifically, it looks like the parameters `initial_IVDOSE_icg_preeq`, `initial_IVDOSE_icg_sim` and the constant `preequilibration_indicator` don't have any values set. All three of those values were added during model import to set condition specific initial conditions in the model. It looks like they don't have any default values set, which is something we should probably fix.
A quick fix is setting those parameters via [setFixedParameterById](https://amici.readthedocs.io/en/latest/generated/amici.amici.Model.html#amici.amici.Model.setFixedParameterById) and [setParameterById](https://amici.readthedocs.io/en/latest/generated/amici.amici.Model.html#amici.amici.Model.setParameterById). However, generally, I would recommend using [simulate_petab](https://amici.readthedocs.io/en/latest/generated/amici.petab_objective.html#amici.petab_objective.simulate_petab) to simulate problems that were imported using petab, as that function automatically sets all of those parameters/constants according to the experimental conditions. For example 
```
from amici.petab_objective import simulate_petab
simulate_petab(petab_problem, amici_model, solver)
```

This currently produces a key error for `Leevy1962_task_icg_iv0.5`, which happens because the condition `Leevy1962_task_icg_iv0.5` is missing in the condition table (there is a `Leevy1962_icg_iv0.5`, which likely needs to be renamed).
A couple of other things I noticed:
- The columns `initializationPriorParameters` and `objectivePriorParameters` in the parameter table should contain numerical values separated by `;`, so `lower bound` and `upper bound` have to replaced by appropriate numerical values
- Noise parameters have to have the respective observableId as suffix, which is not the case for all observables (the respective `model__` prefix is missing.

AMICI doesn't always produce helpful error messages for such issues, as we generally assume that valid PEtab is imported, so it's usually a good idea to validate the model first, e.g., using [petablint](https://petab.readthedocs.io/projects/libpetab-python/en/latest/example/example_petablint.html).

Hope this helps.

Hope this helps

**Comment by matthiaskoenig** [comment]
Hi Florian,
thanks this helps a lot. Makes things much clearer and great information.

I am basically looking for the methods 
* to load a model in AMICI
* make simple model changes
* run a forward simulation
to be able to check that I get the numerical identical results with my models to roadrunner/COPASI before moving on to using AMICI for parameter fitting.

I looked into petab validaton before, but could not find any function in the library for that besides the `petablint` command line script. I looked for a validation function which gives me a computer processable output (such as dict, or JSON) of errors and warnings (see https://github.com/PEtab-dev/libpetab-python/issues/122). I create my petab programmatically and want to run the validation as part of the workflows, not manually.

Thanks for the feedback on the PETab. I will close this issue and replace with a more specific issue for the NaN issues, because I think there should be values via initial conditions or rules in the model for them. Just have to test things out first.

Best Matthias

**Comment by FFroehlich** [comment]
> Hi Florian, thanks this helps a lot. Makes things much clearer and great information.
> 
> I am basically looking for the methods
> 
> * to load a model in AMICI
> * make simple model changes
> * run a forward simulation
>   to be able to check that I get the numerical identical results with my models to roadrunner/COPASI before moving on to using AMICI for parameter fitting.

Yes that makes sense. I think you are already pretty close to achieving that. I suppose something like

```
model.setFixedParameterById('preequilibration_indicator', 0.0) # indicates you want to run simulation, not preequilibration
model.setParameterById('initial_IVDOSE_icg_sim', model.getParameterById('IVDOSE_icg')) # 
model.setParameterById('initial_IVDOSE_icg_preeq', 0.0). # this values doesn't matter
```

Should hopefully get you there. 

However, I am cautiously pessimistic this will actually work, since the generated equations seem fishy. My understading is that `IVDOSE_icg` is a parameter that is part of the bolus/trigger of an event assignment, but model generation ends up applying it to initialise `cum_dose_icg`. Maybe this resolves when other PEtab issues are addressed.

> 
> I looked into petab validaton before, but could not find any function in the library for that besides the `petablint` command line script. I looked for a validation function which gives me a computer processable output (such as dict, or JSON) of errors and warnings (see [PEtab-dev/libpetab-python#122](https://github.com/PEtab-dev/libpetab-python/issues/122)). I create my petab programmatically and want to run the validation as part of the workflows, not manually.
> 

See response in the respective issue.

> Thanks for the feedback on the PETab. I will close this issue and replace with a more specific issue for the NaN issues, because I think there should be values via initial conditions or rules in the model for them. Just have to test things out first.

For all of the parameter there are, but those three additional parameters that cause trouble don't have any default value set since AMICI add's them to the model in order to be able to account for preequilibration during sensitivity computations.


> Best Matthias

**Comment by matthiaskoenig** [comment]
Sorry Fabian, realized I wrote the wrong name ;)

* Working on two different model versions. The first one is without the events and uses the rate rules. This should work already as soon as I fix my petab issues.
* I could get the simulation running with AMICI after understanding the difference between the petab functions and the amici functions
* I am not sure what the best way is to implement the multiple dosing protocols in SBML which result in these strange events. I have to give repeated doses (e.g. every 24 hrs) which are added to a pool of total dose which is slowly absorbed, but not within 24 hrs. So I have to keep track of the pool of dose which is not yet absorbed. So what I am doing is to copy the given dose immediatly over to the total dose pool via an event. Otherwise if I only have one pool I can not set it to `current_dose + new_dose` which is what the event is doing. Unfortunately, I will probably need this events here.

**Comment by matthiaskoenig** [comment]
Thanks again for the great answer. This solved this issue.
