### ISSUE TITLE
Timepoints in simulation with forward sensitivities

### ISSUE THREAD

**Issue by aidinbii** [AMICI-dev/AMICI#1995]
Hello,
Could you please help me explaining this behaviour
```
model_module = amici.import_model_module(model_name, model_output_dir)
model_sens = model_module.getModel()

solver_sens_forw = model_sens.getSolver()
solver_sens_forw.setSensitivityMethod(amici.SensitivityMethod.forward)
solver_sens_forw.setSensitivityOrder(amici.SensitivityOrder.first)

model_sens.setParameters(np.power(10,testpars).flatten()) # in lin scale
```
when I run a simulation with these timepoints
```
model_sens.setTimepoints([0.0, 500.0])
rdata_sens_forw = amici.runAmiciSimulation(model_sens, solver_sens_forw)
```
I get an error
```
[Warning] AMICI:CVODES:CVode:ERR_FAILURE: AMICI ERROR: in module CVODES in function CVode : At t = 101.227 and h = 3.5362e-06, the error test failed repeatedly or with |h| = hmin. 
[Warning] AMICI:simulation: AMICI forward simulation failed at t = 101.227448:
AMICI failed to integrate the forward problem
```

Same error, if I run: 
```
model_sens.setTimepoints([500.0])
rdata_sens_forw = amici.runAmiciSimulation(model_sens, solver_sens_forw)
```

but with:
```
model_sens.setTimepoints([250.0, 500.0])
rdata_sens_forw = amici.runAmiciSimulation(model_sens, solver_sens_forw)
```
or
```
model_sens.setTimepoints([250.0])
rdata_sens_forw = amici.runAmiciSimulation(model_sens, solver_sens_forw)
```
it ends successfully.

Thanks

**Comment by FFroehlich** [comment]
Hi @aidinbii,

Amici will force the ODE solver to stop at the specified timepoints. In general, this shouldn't affect integration errors, but if it does, it's likely a good idea to change integration tolerances using [solver.setRelativeTolerance](https://amici.readthedocs.io/en/latest/generated/amici.amici.Solver.html#amici.amici.Solver.setRelativeTolerance) and [solver.setAbsoluteTolerance](https://amici.readthedocs.io/en/latest/generated/amici.amici.Solver.html#amici.amici.Solver.setAbsoluteTolerance).

I would guess that you need to lower those tolerances (this is may seem a bit paradoxical, but lower tolerance may prevent, e.g., negative blow-up after solutions become negative due to integration errors).

**Comment by aidinbii** [comment]
@FFroehlich, I will try that

I forgot to mention that with adjoint sensitivities it works for any timepoints

**Comment by FFroehlich** [comment]
> @FFroehlich, I will try that
> 
> I forgot to mention that with adjoint sensitivities it works for any timepoints

Forward sensitivity computations run simultaneously with the simulation and joint error control will be applied to both. Adjoint sensitivity computations run after the simulation and have no effect on it. Again, ideally there should barely be any differences and if there are, it indicates that tolerances are off.
