### ISSUE TITLE
Docker release images are no longer published

### ISSUE THREAD

**Issue by FFroehlich** [AMICI-dev/AMICI#2383]
https://hub.docker.com/r/dweindl/amici/tags?page=1

latest & develop get pushed but last versioned tag was 0.20.0

**Comment by dweindl** [comment]
The recent release images got pushed, but only as `latest` and not with the respective version number. Those previous ones with version numbers were only the release branches, not the actual release-tagged commits. It was never set up properly and I agree that it would be good to change that. That those release branches didn't get published was because I created them from my fork.
