### ISSUE TITLE
Setup schema and import for YAML-based ODE models

### ISSUE THREAD

**Issue by dweindl** [AMICI-dev/AMICI#863]
See discussion in #855 

- [x] RateRules #857 
- [x] YAML import
- [x] YAML schema
- [ ] Test cases (current Matlab syms files)

**Comment by paulstapor** [comment]
Let's revive this discussion.
@jvanhoefer suggested to use https://github.com/martamatos/yaml2sbml for importing yaml based models via SBML.
I think it's pretty neat, I also like the yaml2petab-importer there, which directly creates an observable file.
However, if we want to use this, there are some things to be discussed:
 * Is the packages sufficiently maintained (i.e., what happens if petab-api changes? Who takes care of it?)
 * How do we want to handle installation, in case we want to use it? Fork the repo to AMICI-dev, having a subrepo of AMICI, downloading from the current repo from martamatos site, or adding an auto-deploy from martamatos repo to PyPI, to simply install via pip and PyPI?
 * How about tests concerning the importer? Does it cover enough functionality?

Any more ideas/thoughts on this? Would be actually happy to have this yaml-importer...

**Comment by FFroehlich** [comment]
Any plans to include events in that schema? I think from an amici perspective, would probably handle this the same way as other formats are currently handled, vial a convenience wrapper that simply generates a temporary sbml file which is then compile. Would be great if the package was available via pip and could then be specified as optional dependency as done with pysb.

**Comment by dweindl** [comment]
> I think from an amici perspective, would probably handle this the same way as other formats are currently handled, vial a convenience wrapper that simply generates a temporary sbml file which is then compile.

As this is all about model conversion which is completely independent of any AMICI functionality, I don't think it is helpful to wrap that. That will pretty much save you only one line of code (or half, because the argument list of the wrapper will get longer)...

**Comment by jvanhoefer** [comment]
> Any plans to include events in that schema?

We could. There were plans of this, but this was not pursued any further recently. If you have an application for events in `yaml2sbml` or would like to have events (in case we integrate `yaml2sbml` into AMICI), I am happy to add them. :)

**Comment by dweindl** [comment]
I think this can be closed. [yaml2sbml](https://github.com/yaml2sbml-dev/yaml2sbml) is referenced in the docs.
